---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-tf
spec:
  interval: 60s
  url: https://github.com/tatari-tv/tf-controller-helloworld
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: demo-tf
spec:
  path: ./terraform
  approvePlan: ""
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: demo-tf
  writeOutputsToSecret:
    name: helloworld-outputs
